### ISSUE TITLE
Missing Information from Documentation...

### ISSUE THREAD

**Issue by thomasdola** [mvdwg/phoenix_components#13]
Thank you for this awesome library, but one thing i did not get was:

- What are the benefits for using it.

This question because some of us are newbies. Just a little bit of clarification on this aspect would help.

Thanks

**Comment by san650** [comment]
Thanks @thomasdola for opening this issue.

I'll try to come up with a good explanation of why this library exists but I'll try to answer the question right now.

__Phoenix partials and helpers are not enough.__

Let's say you want to have a piece of HTML that you're going to use in several templates across controllers.

```html
<div class="modal">
  <h1>@title</h1>
  <!-- modal content -->
</div>
```

The alternatives are:
1. Have two partials -- one for the modal header and one for the modal footer

```eex
<%= render "modal_header.html", title: "Create user" %>
<!-- user form goes here -->
<%= render "modal_footer.html" %>
```

2. Another approach would be to have a helper in the view that does something similar to the above

```eex
<%= modal_header %>
<!-- user form goes here -->
<%= modal_footer %>
```

3. The third option is to combine helpers and partials to have something similar to a component

/web/templates/_modal.html.eex
```eex
<div class="modal">
  <h1>@title</h1>
  @content
</div>
```

and a helper function in a view that does something like

```ex
def modal(do: content) do
  render AView, "_modal.html", content: content
end
```

---

This library wraps the last option (3) into a reusable patter by letting you create templates and views that behave like a component.

The library tries to propose a convention on how to create these reusable components and where to place them.

Just a heads up, I'm working on it heavily to wrap up the version 1 which will have what I consider the minimum amount of features to make it production ready.

Please, let me know you feedback!

**Comment by thomasdola** [comment]
Thanks for this expiation. 
How soon can we expect the production ready version?

**Comment by san650** [comment]
@thomasdola v1.02 should be consider production ready!
